// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Backend
export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const ORGANS_RESET = 'ORGANS_RESET';
export const ORGANS_START = 'ORGANS_START';
export const ORGANS_SUCCESS = 'ORGANS_SUCCESS';
export const ORGANS_FAIL = 'ORGANS_FAIL';

export const UNITS_RESET = 'UNITS_RESET';
export const UNITS_START = 'UNITS_START';
export const UNITS_SUCCESS = 'UNITS_SUCCESS';
export const UNITS_FAIL = 'UNITS_FAIL';

export const BUILDERS_RESET = 'BUILDERS_RESET';
export const BUILDERS_START = 'BUILDERS_START';
export const BUILDERS_SUCCESS = 'BUILDERS_SUCCESS';
export const BUILDERS_FAIL = 'BUILDERS_FAIL';

export const CUSTOMERS_RESET = 'CUSTOMERS_RESET';
export const CUSTOMERS_START = 'CUSTOMERS_START';
export const CUSTOMERS_SUCCESS = 'CUSTOMERS_SUCCESS';
export const CUSTOMERS_FAIL = 'CUSTOMERS_FAIL';

export const ACTIONS_RESET = 'ACTIONS_RESET';
export const ACTIONS_START = 'ACTIONS_START';
export const ACTIONS_SUCCESS = 'ACTIONS_SUCCESS';
export const ACTIONS_FAIL = 'ACTIONS_FAIL';

export const SELLS_RESET = 'SELLS_RESET';
export const SELLS_START = 'SELLS_START';
export const SELLS_SUCCESS = 'SELLS_SUCCESS';
export const SELLS_FAIL = 'SELLS_FAIL';

export const MAINTENANCES_RESET = 'MAINTENANCES_RESET';
export const MAINTENANCES_START = 'MAINTENANCES_START';
export const MAINTENANCES_SUCCESS = 'MAINTENANCES_SUCCESS';
export const MAINTENANCES_FAIL = 'MAINTENANCES_FAIL';

export const GAUGINGS_RESET = 'GAUGINGS_RESET';
export const GAUGINGS_START = 'GAUGINGS_START';
export const GAUGINGS_SUCCESS = 'GAUGINGS_SUCCESS';
export const GAUGINGS_FAIL = 'GAUGINGS_FAIL';

export const VEHICLES_RESET = 'VEHICLES_RESET';
export const VEHICLES_START = 'VEHICLES_START';
export const VEHICLES_SUCCESS = 'VEHICLES_SUCCESS';
export const VEHICLES_FAIL = 'VEHICLES_FAIL';

export const VEHICLE_TYPES_RESET = 'VEHICLE_TYPES_RESET';
export const VEHICLE_TYPES_START = 'VEHICLE_TYPES_START';
export const VEHICLE_TYPES_SUCCESS = 'VEHICLE_TYPES_SUCCESS';
export const VEHICLE_TYPES_FAIL = 'VEHICLE_TYPES_FAIL';